<?php

namespace QH\Product\Repositories\Product\Element;

use Illuminate\Support\Facades\File;
use QH\Core\Base\Repository\BaseRepository;
use QH\Product\Models\Category\Category;
use QH\Product\Models\Product\Product;
use QH\Product\Repositories\Product\Interface\ProductRepositoryInterface;
use App\Models\User;



class ProductRepository extends BaseRepository implements ProductRepositoryInterface
{
    //lấy model tương ứng
    public function getModel()
    {
        return Product::class;
    }

    public function getProduct()
    {
        return $this->model->select('name')->take(2)->get();
    }

    public function getUserById($id)
    {
        return User::find($id)->first();
    }

    public function getAllCategories()
    {
        $categories = Category::all();
        return $categories;
    }

    public function getAllUsers()
    {
        $users = User::all();
        return $users;
    }

    public function deleteAndUnlinkImage($product)
    {
        // $this->delete($id);
        $product = $this->model->find($product->id);
        $this->UnlinkImage($product);
        return parent::delete($product);
    }

    public function UnlinkImage($product)
    {
        if ($product) {
            $thumbnailPath = public_path($product->thumb);
            if (File::exists($thumbnailPath)) {
                try {
                    unlink($thumbnailPath);
                    // File deletion successful
                } catch (\Exception $e) {
                    \Log::error('Error deleting thumbnail: ' . $e->getMessage());
                }
            } else {
                \Log::error('File not found: ' . $thumbnailPath);
            }
        }
    }

    public
    function getAllProducts()
    {
        return Product::with("category")->with("user")->orderByDesc("id")->paginate(3);
    }

    public function createProduct($request)
    {
        $userId = auth()->user()->id;
        $author = $this->getUserById($userId);
        $request['author_id'] = $author->id;
        $request['author_type'] = $author->type;
        $data = $request->except('_token');
        return parent::create($data); // TODO: Change the autogenerated stub
    }
    public function updateProduct($product, $data){
        $this->UnlinkImage($product);
        return parent::update($product, $data);
    }
}
